config:
  aws:region: us-east-1
  grug:env: prod
  grug:domain: grug.lol
secretsprovider: awskms://alias/pulumi-secrets?region=us-east-1
encryptedkey: AQICAHhjW4kuB5Y5Y/O/7WODHZsdeqg+NIKyRB1FUcpCkpgCyAGvNgCdtmWOJTfYTEVzY9k6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNE/b/yf16Ff2mUGsAgEQgDtASj9TpRkGzRddSu7P5cCsAqYNtnyc1CVmtdn1jBJPrtu2pQE5pOeVGYA5Q8Jt/4CSkzd738TbAbcj/g==
